/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tfdesign;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.HashMap;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Isaac Sudhan
 */
public class JDFrame extends javax.swing.JFrame {
    private final UIListener listener;
    private MyWorker w=null;
    private HashMap<Integer, Double> lengthMap;
    private HashMap<Integer, Double> breadthMap;
    private static boolean changed=false;

    /**
     * Creates new form JDFrame
     */
    
    public JDFrame(UIListener l) {
        super("Core Design");
        initComponents();
        init2();
        this.listener =l;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDrawingPanel = new javax.swing.JPanel();
        jKVA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPhase = new javax.swing.JTextField();
        jFreq = new javax.swing.JTextField();
        jFluxDensity = new javax.swing.JTextField();
        jStackingFactor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);

        jScrollPane1.setPreferredSize(null);

        jDrawingPanel.setPreferredSize(new java.awt.Dimension(700, 432));

        javax.swing.GroupLayout jDrawingPanelLayout = new javax.swing.GroupLayout(jDrawingPanel);
        jDrawingPanel.setLayout(jDrawingPanelLayout);
        jDrawingPanelLayout.setHorizontalGroup(
            jDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jDrawingPanelLayout.setVerticalGroup(
            jDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jDrawingPanel);

        jLabel1.setText("KVA:");

        jK.setText("0.45");

        jLabel2.setText("K:");

        jLabel3.setText("Phase:");

        jLabel4.setText("Freq:");

        jLabel5.setText("Flux Density:");

        jLabel6.setText("Stacking Factor: ");

        jPhase.setText("3");

        jFreq.setText("50");

        jFluxDensity.setText("1.8");

        jStackingFactor.setText("0.5");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(164, 164, 164)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPhase, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jK, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jFreq)
                        .addComponent(jKVA, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jStackingFactor)
                        .addComponent(jFluxDensity, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(395, 395, 395))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFluxDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jStackingFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init2(){
        jKVA.getDocument().addDocumentListener(new DocuListen());
        jK.getDocument().addDocumentListener(new DocuListen());
        jFreq.getDocument().addDocumentListener(new DocuListen());
        jFluxDensity.getDocument().addDocumentListener(new DocuListen());
        jPhase.getDocument().addDocumentListener(new DocuListen());
        jStackingFactor.getDocument().addDocumentListener(new DocuListen());
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(w==null){
            w=new MyWorker();w.execute();
        }else if(changed){
            w=new MyWorker();
            w.execute();
            changed=false;
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jKVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKVAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void lookNFeel(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    
    class MyWorker extends SwingWorker<Boolean, Void>{
        

        @Override
        protected Boolean doInBackground() throws Exception {
            try{
                double kva=Double.parseDouble(jKVA.getText());
                
                double k=Double.parseDouble(jK.getText());
                double NoOfPhase=Double.parseDouble(jPhase.getText());
                double freq=Double.parseDouble(jFreq.getText());
                double fluxDensity=Double.parseDouble(jFluxDensity.getText());
                double ki=Double.parseDouble(jStackingFactor.getText());
                double eT=k*Math.sqrt(kva);
                double flux=eT/(4.44*freq);
                double effIronArea=flux/fluxDensity;
                double grossTronArea=effIronArea/ki;
                listener.setReqArea(grossTronArea*1000000);
                listener.startDesign();
                lengthMap = listener.getLengthMap();
                breadthMap = listener.getBreadthMap();
                if(lengthMap==null||breadthMap==null){return false;}
                
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(JDFrame.this,"InValid Input \n Enter Only Numbers" , "Error", JOptionPane.ERROR_MESSAGE);
            }
            return true;
        }

        @Override
        protected void done() {
            super.done(); 
            try {
                boolean g=get();
                System.out.println("G: "+g);
                if(g){
                    jDrawingPanel=new DrawingBoard();
                    jDrawingPanel.setPreferredSize(new java.awt.Dimension(700, 432));
                    javax.swing.GroupLayout jDrawingPanelLayout = new javax.swing.GroupLayout(jDrawingPanel);
                    jDrawingPanel.setLayout(jDrawingPanelLayout);
                    jDrawingPanelLayout.setHorizontalGroup(
                        jDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 700, Short.MAX_VALUE)
                    );
                    jDrawingPanelLayout.setVerticalGroup(
                        jDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 432, Short.MAX_VALUE)
                    );

        
                    jScrollPane1.setViewportView(jDrawingPanel);
                    //jDrawingPanel.setSize(1000, 1000);
                    jDrawingPanel.repaint();
                }
                    
            } catch (    InterruptedException | ExecutionException ex) {
                Logger.getLogger(JDFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }
    
    class DrawingBoard extends JPanel {
        
            
            @Override
            public void paint(Graphics gi) {
                super.paint(gi);
                 //To change body of generated methods, choose Tools | Templates.
                
                if(lengthMap !=null && breadthMap!=null){
//                    System.out.println("painting");
                    Graphics2D g = (Graphics2D) gi;
                    int x,y;
                    x=100;y=300;
                    int xi=new Double(lengthMap.get(0)).intValue();
                    int yi=new Double(breadthMap.get(0)).intValue();
                    g.drawRect(x, y-yi/2, xi, yi);
                    int y1=y;
                    int y2=y;
                    int l=lengthMap.size();
                    for(int i=1;i<l;i++){
                        int p=new Double(lengthMap.get(i)).intValue();
                        x=x+10;
                        int q=new Double(breadthMap.get(i)).intValue();
                        int preq=new Double(breadthMap.get(i-1)).intValue();
                        q=q/2;
                        if(i==1){y1=y1-(preq/2)-q;}else{y1=y1-q;}
                        g.drawRect(x, y1, p, q);
                        y2=y2+(preq/2);
                        g.drawRect(x, y2, p, q);
                    }
                }
                
            }
            
        }
    
    class DocuListen implements DocumentListener{

        @Override
        public void insertUpdate(DocumentEvent e) {
            changed=true;
            //System.out.println("insertUpdate");
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            changed=true;
            //System.out.println("removeUpdate");
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            changed=true;
            //System.out.println("changedUpdate");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jDrawingPanel;
    private javax.swing.JTextField jFluxDensity;
    private javax.swing.JTextField jFreq;
    private javax.swing.JTextField jK;
    private javax.swing.JTextField jKVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jPhase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jStackingFactor;
    // End of variables declaration//GEN-END:variables
}
